version: '3.8'

services:
  app:
    container_name: backend-unipath
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=unipath
      - REDIS_URL=redis://redis-unipath:6379
    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - /app/node_modules
      - ./csv-file:/app/csv-file

  mysql:
    image: mysql:8.0
    container_name: mysql-unipath
    command: --local-infile=1
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=unipath
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis-be:
    image: redis:7
    container_name: redis-unipath
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mysql_data:
  redis_data: